# Generated by Django 5.2 on 2025-05-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_rename_medical_clearance_riskassessment_medical_clearance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
