# Generated by Django 5.2 on 2025-05-12 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_patient_religion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='pwd_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='pwd_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='pwd_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pwd', to=settings.AUTH_USER_MODEL),
        ),
    ]
