# Generated by Django 5.2.1 on 2025-05-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_riskassessment_pwd_verification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
