# Generated by Django 5.2.1 on 2025-05-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_medicalrequirement_reviewed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentalhealthrecord',
            name='notes',
        ),
        migrations.AddField(
            model_name='mentalhealthrecord',
            name='certification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentalhealthrecord',
            name='prescription_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealthrecord',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to='medical/mental_health/certifications/'),
        ),
        migrations.AlterField(
            model_name='mentalhealthrecord',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='medical/mental_health/prescriptions/'),
        ),
        migrations.AlterField(
            model_name='mentalhealthrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
