# Generated by Django 5.2.1 on 2025-05-22 23:21

import medical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_remove_mentalhealthrecord_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=medical.models.profile_picture_path),
        ),
        migrations.AlterField(
            model_name='mentalhealthrecord',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to=medical.models.MentalHealthRecord.certification_path),
        ),
        migrations.AlterField(
            model_name='mentalhealthrecord',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to=medical.models.MentalHealthRecord.prescription_path),
        ),
    ]
