# Generated by Django 5.2.1 on 2025-05-29 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_patient_profile_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='student',
        ),
        migrations.RemoveField(
            model_name='physicalexamination',
            name='student',
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_examination', to='medical.patient'),
        ),
        migrations.AlterField(
            model_name='dentalrecords',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.patient'),
        ),
        migrations.AlterField(
            model_name='emergencyhealthassistancerecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.patient'),
        ),
        migrations.AlterField(
            model_name='medicalrequirement',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.patient'),
        ),
        migrations.AlterField(
            model_name='mentalhealthrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='examination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_for_examination', to='medical.physicalexamination'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.patient'),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.patient'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='clearance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.patient'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.patient'),
        ),
    ]
