# Generated by Django 5.2.1 on 2025-05-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_remove_patient_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
