# Generated by Django 5.2.1 on 2025-05-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0014_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
