# Generated by Django 5.2.1 on 2025-05-30 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_faculty_faculty_id_faculty_middlename_faculty_sex'),
        ('medical', '0016_alter_patient_academic_year_alter_patient_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrequirement',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.faculty'),
        ),
        migrations.AddField(
            model_name='mentalhealthrecord',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.faculty'),
        ),
    ]
