# Generated by Django 5.2.1 on 2025-05-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_faculty_faculty_id_faculty_middlename_faculty_sex'),
        ('medical', '0017_medicalrequirement_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequest',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.faculty'),
        ),
    ]
