# Generated by Django 5.2.1 on 2025-05-30 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_faculty_faculty_id_faculty_middlename_faculty_sex'),
        ('medical', '0018_patientrequest_faculty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrequest',
            name='approve',
        ),
        migrations.RemoveField(
            model_name='patientrequest',
            name='date_approved',
        ),
        migrations.RemoveField(
            model_name='patientrequest',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='date_responded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FacultyRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_responded', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faculty')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_faculty_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Request',
                'verbose_name_plural': 'Faculty Requests',
                'ordering': ['-date_requested', 'is_urgent'],
            },
        ),
    ]
