# Generated by Django 5.2.1 on 2025-05-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0019_remove_patientrequest_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyrequest',
            name='is_mental_health_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrequirement',
            name='mental_health_availed_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentalhealthrecord',
            name='service_availed_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='is_mental_health_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facultyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
