# Generated by Django 5.2.1 on 2025-05-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0020_facultyrequest_is_mental_health_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentalhealthrecord',
            old_name='service_availed_admin',
            new_name='is_availing_mental_health',
        ),
        migrations.RemoveField(
            model_name='facultyrequest',
            name='is_mental_health_request',
        ),
        migrations.RemoveField(
            model_name='medicalrequirement',
            name='mental_health_availed_by_user',
        ),
        migrations.RemoveField(
            model_name='patientrequest',
            name='is_mental_health_request',
        ),
        migrations.AlterField(
            model_name='facultyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
