# Generated by Django 5.2.1 on 2025-05-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0021_rename_service_availed_admin_mentalhealthrecord_is_availing_mental_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalhealthrecord',
            name='is_availing_mental_health',
            field=models.BooleanField(default=False),
        ),
    ]
