# Generated by Django 5.2.1 on 2025-05-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0023_merge_mental_health_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealthrecord',
            name='is_availing_mental_health',
            field=models.BooleanField(default=False),
        ),
    ] 