# Generated by Django 5.2.1 on 2025-06-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0024_alter_mentalhealthrecord_is_availing_mental_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrequirement',
            name='pwd_card_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ] 