# Generated by Django 5.2.1 on 2025-06-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0025_medicalrequirement_pwd_card_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalrecords',
            name='date_appointed',
            field=models.DateTimeField(null=True),
        ),
    ]
